/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Rent } from "./Rent";
export * as factories from "./factories";
export { Rent__factory } from "./factories/Rent__factory";
